---
repos:
  - destination: '/home/vagrant/source'
    domain: 'github.com/bitbucket.org'
    name: 'my_project'
    pass: 'test'
    postinstall: 'generic_rails_app_setup.sh'
    type: 'git'
    user: 'username'
...
